import React from "react";

const page = () => {
  return (
    <div>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
    </div>
  );
};

export default page;
